/**
 * Download Link Extension
 * 
 * Renders download buttons for files generated by the backend.
 * Handles message.download events from OptOrch orchestration nodes.
 */

export default {
  id: 'download-link',
  name: 'Download Link Extension',
  
  /**
   * Detect if this extension should handle the event
   * @param {Object} event - SSE event from backend
   * @param {string} event.type - Event type identifier
   * @param {Object} event.data - Event payload
   * @returns {boolean} True if this extension handles the event
   */
  canHandle: (event) => {
    return event.type === 'message.download';
  },
  
  /**
   * Render custom UI for download event
   * @param {Object} event - SSE event data
   * @param {Object} context - Rendering context from chat widget
   * @returns {JSX.Element} React component to render
   */
  renderContent: (event, context) => {
    const { filename, download_id } = event;
    const codeBlocks = document.querySelectorAll('pre code');
    codeBlocks.forEach(code => {
      const text = code.textContent?.trim() || '';
      const pre = code.parentElement;
      if (!pre) return;
      
      const looksLikeCode = /^(function|const|let|var|class|import|export|async|await|return|\{|\[)/m.test(text) ||
                            /[;{}()\[\]]/g.test(text) ||
                            text.split('\n').length > 2;
      
      const isLanguageTag = /^(json|javascript|python|typescript|jsx|tsx)$/i.test(text);
      const isEmpty = text.length === 0;
      
      if (isEmpty || isLanguageTag || (!looksLikeCode && text.length < 50)) {
        pre.style.display = 'none';
      }
    });
    
    if (!filename || !download_id) {
      return (
        <div className="p-4 border border-red-300 bg-red-50 dark:bg-red-950 rounded-lg">
          <p className="text-sm text-red-700 dark:text-red-300">
            ❌ Invalid download event - missing filename or download_id
          </p>
        </div>
      );
    }
    
    const handleDownload = () => {
      const downloadUrl = event.url
        ? `${context.apiBaseUrl || ''}${event.url}`
        : `${context.apiBaseUrl || ''}/downloads/${download_id}`;
      window.open(downloadUrl, '_blank');
    };
    
    return (
      <div className="inline-block mt-4 p-4 border border-blue-200 dark:border-blue-800 bg-blue-50 dark:bg-blue-950 rounded-lg shadow-md">
        <div className="flex items-start gap-3">
          <div className="flex-shrink-0 w-10 h-10 rounded-full bg-blue-100 dark:bg-blue-900 flex items-center justify-center">
            <span className="text-xl">📄</span>
          </div>
          <div className="flex-1 min-w-0">
            <div className="flex gap-1">
              <h4 className="flex-none font-semibold text-xs text-blue-900 dark:text-blue-200 mb-1">File Ready</h4>
              <p className="flex-none text-xs text-blue-700 dark:text-blue-300 truncate mb-3">{filename}</p>
            </div>
            <button
              onClick={handleDownload}
              className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-md text-sm font-medium transition-colors flex items-center gap-2"
            >
              <span>⬇</span>Download File
            </button>
          </div>
        </div>
      </div>
    );
  },  
};
